name = "stashit-api"
main = "src/index.ts"

# Use the latest compatibility date for modern Node.js support
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Auth Database (shared by all users)
[[d1_databases]]
binding = "AUTH_DB"
database_name = "stashit-auth"
database_id = "1e950ca2-6104-4298-bd85-4c6a65d83145"
migrations_dir = "db/migrations"

# Template Database (for creating new user DBs)
[[d1_databases]]
binding = "DB"
database_name = "stashit-template"
database_id = "0d088c9a-f54e-4c76-8215-a2a3b9c5fd18"
migrations_dir = "db/migratioins"

[vars]
NODE_ENV = "development"
FRONTEND_URL = "http://localhost:5173"
API_BASE_URL = "http://localhost:8787"
BETTER_AUTH_SECRET = "B5iz0NibwJLRdgeWmrr72c1Nc6lj0GHgUJObXTk1q+4=" 
BETTER_AUTH_URL = "http://localhost:8787"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
# These should ideally be secrets (wrangler secret put), but kept here for dev
FROM_EMAIL = "onboarding@resend.dev"
RESEND_API_KEY = "re_4xdNRKUs_9V1uM3bNJ94hMmHu1toxU5Fc"

# ImageKit Configuration
IMAGEKIT_PUBLIC_KEY="public_xXg3EBjK/10aCwEL0ws7SEmIMSA="
IMAGEKIT_PRIVATE_KEY="private_qqHC6aK3bvbnlsA3oA/s1pHw85c="
IMAGEKIT_URL_ENDPOINT="https://ik.imagekit.io/k5h5mbfmd"
